### PR TITLE
Fix/tasks home list

### LINKED ISSUE #162: Remove space between tasks list in home when there is only one element in the grid
Image

### PR DESCRIPTION
**Pull request by hagarabobakr**
## 🛠️ Summary

Fix three issues. 

---

## 📌 Description

fix https://github.com/SanaaTeam/TudeeAssistant/issues/162, https://github.com/SanaaTeam/TudeeAssistant/issues/155, https://github.com/SanaaTeam/TudeeAssistant/issues/165 and https://github.com/SanaaTeam/TudeeAssistant/issues/154

image

### CODE REVIEW

**Review by mostafa-n3ma — DISMISSED** [review]
thank you

**Review by haideraljawasim — DISMISSED** [review]

**Review by ZainabAlnajjar — DISMISSED** [review]
nice work, but there is a small isuee, please check my comment

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt [hunk 1]
```diff
@@ -297,9 +298,21 @@ private fun CategoryList(
     categories: List<CategoryUiState>,
     onClick: (TaskUiState) -> Unit,
 ) {
+    val rowCount = if (items.size == 1) 1 else 2
+    val cardHeight = 111.dp
+    val targetHeight = if (items.isNotEmpty()) {
+        (cardHeight * rowCount) + Theme.dimension.extraLarge
+    } else {
+        0.dp
+    }
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt:307]: This part could be improved,
First, we should not use complex calculation inside a composable, since it is only two cases, I think you can add them directly

Secondly, you are not taking the padding between the cards into consideration `verticalArrangement = Arrangement.spacedBy(Theme.dimension.small)`, that is why the description text seems like it was cut off a bit when there are two rows

and lastly, we can return from this composable if the list is empty, so we won't need to compile all this code while we don't need it

these lines could be like this: 


```
 if (items.isEmpty()) return
    val rowCount = if (items.size > 1) 2 else 1
    val animatedHeight by animateDpAsState(
        targetValue = if (items.size == 1)  111.dp  else 222.dp + Theme.dimension.small + Theme.dimension.extraLarge ,
        label = "gridHeight"
    )
```

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt [hunk 2]
```diff
@@ -297,9 +298,21 @@ private fun CategoryList(
...
+
+    val animatedHeight by animateDpAsState(
+        targetValue = targetHeight,
+        label = "gridHeight"
+    )
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt]: This part could be improved,
First, we should not use complex calculation inside a composable, since it is only two cases, I think you can add them directly

Secondly, you are not taking the padding between the cards into consideration `verticalArrangement = Arrangement.spacedBy(Theme.dimension.small)`, that is why the description text seems like it was cut off a bit when there are two rows

and lastly, we can return from this composable if the list is empty, so we won't need to compile all this code while we don't need it

these lines could be like this: 


```
 if (items.isEmpty()) return
    val rowCount = if (items.size > 1) 2 else 1
    val animatedHeight by animateDpAsState(
        targetValue = if (items.size == 1)  111.dp  else 222.dp + Theme.dimension.small + Theme.dimension.extraLarge ,
        label = "gridHeight"
    )
```

Comment (hagarabobakr) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreen.kt]: Thank you zainab

**Review by EL-MANCY — APPROVED** [review]
Great Job Hajar

**Review by Ahmed7osny1 — APPROVED** [review]
