### PR TITLE
Fix Multiple Issues in the home Screen Behaviour

### LINKED ISSUE #177: refactor Home Screen Behaviour

### PR DESCRIPTION
**Pull request by EL-MANCY**
## 🛠️ Summary

make the snackbar function more general in the HomeScreen.kt fix the behaviour of [switching tasks status] & [updating the tasks list after any action]

---

## 📌 Description

make the snackbar function more general in the HomeScreen.kt fix the behaviour of [switching tasks status] & [updating the tasks list after any action] - [All interactions of the users are now in the interaction listener] - [ Broke down the composobles to files for readability]
 
---

## ✅️Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactoring (no functional changes, renaming)

### CODE REVIEW

**Review by haideraljawasim — DISMISSED** [review]

**Review by hagarabobakr — DISMISSED** [review]

**Review by diyar214 — DISMISSED** [review]
LGTM!

**Review by Ahmed7osny1 — DISMISSED** [review]

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenInteractionsListener.kt [hunk 1]
```diff
@@ -4,8 +4,8 @@ import com.sanaa.tudee_assistant.presentation.model.TaskUiState
 
 interface HomeScreenInteractionsListener {
     fun onToggleColorTheme()
-    fun onAddTaskSuccess()
-    fun onAddTaskHasError(errorMessage: String)
+    fun snackBarSuccess(message: String)
+    fun snackBarError(errorMessage: String)
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenInteractionsListener.kt]: function name should start with verb, change to `onSnackBarSuccess` and `onSnackBarError`

Comment (EL-MANCY) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenInteractionsListener.kt]: all deleted now

File: app/src/main/res/values/strings.xml
Comment (ZainabAlnajjar) [inline app/src/main/res/values/strings.xml:1]: there are duplicated strings for the task snackbar message, please unify them into one string

Comment (EL-MANCY) [reply app/src/main/res/values/strings.xml:1]: I think thats due the merges

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenInteractionsListener.kt
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/home/HomeScreenInteractionsListener.kt:1]: no need for the comments on this file, please remove them

**Review by hagarabobakr — DISMISSED** [review]
Great 👏

**Review by hagarabobakr — APPROVED** [review]

**Review by hagarabobakr — DISMISSED** [review]

**Review by hagarabobakr — DISMISSED** [review]

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/composable/bottomSheet/task/taskDetailsBottomSheet/TaskDetailsComponent.kt [hunk 2]
```diff
@@ -134,9 +134,9 @@ fun TaskDetailsComponent(
                                     interactionListener.onMoveTaskToAnotherStatus(
                                         onMoveStatusSuccess = { newStatus ->
                                             onMoveStatusSuccess(newStatus)
-                                            if (newStatus == TaskUiStatus.DONE) {
-                                                onDismiss()
-                                            }
+//                                            if (newStatus == TaskUiStatus.DONE) {
+//                                                onDismiss()
+//                                            }
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/composable/bottomSheet/task/taskDetailsBottomSheet/TaskDetailsComponent.kt]: delete the comment

Comment (EL-MANCY) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/composable/bottomSheet/task/taskDetailsBottomSheet/TaskDetailsComponent.kt]: okay

**Review by hagarabobakr — APPROVED** [review]

**Review by ZainabAlnajjar — APPROVED** [review]

**Review by haideraljawasim — APPROVED** [review]
