### PR TITLE
Fix/text field

### LINKED ISSUE #147: There’s no limit on task title length and the description text field only supports one line.
[There’s no limit on task title length and the description text field only supports one line.](https://thechance-workspace.slack.com/archives/C08SKLP23EX/p1750891199699599?thread_ts=1750844673.545889&cid=C08SKLP23EX)

### PR DESCRIPTION
**Pull request by hagarabobakr**
## 🛠️ Summary

fix https://github.com/SanaaTeam/TudeeAssistant/issues/147

image

### CODE REVIEW

**Review by haideraljawasim — APPROVED** [review]

**Review by ZainabAlnajjar — CHANGES_REQUESTED** [review]
the lines limit is not working, and I think there is a better way to do it, please check on my comment

File: app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt [hunk 1]
```diff
@@ -94,6 +94,8 @@ fun AddEditTaskContent(
                         .height(168.dp)
                         .padding(bottom = Theme.dimension.medium),
                     keyboardOptions = KeyboardOptions.Default.copy(imeAction = ImeAction.Done),
+                    maxLines = 10,
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: please check this limit again, I could type more than 10 lines
image

another thing, I believe this will only limit the display of the text and not the text value, 
and even if it worked, I don't think this is the correct way to limit the user input because the line length could change depending on the screen size, therefor you could type more or less if you rotate the device for example or used different screen size

a better way could be by moving the length condition to the` onValueChange = listener::onDescriptionChange`, where the viewModel won't update the state if the string exceeded the max length, let's say 200 characters for example, could also check for "\n" count not exceed 10 also, just to ensure they dont but each char at a line

Comment (mostafa-n3ma) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: The problem is with the display 
let the viewModel update any text size but don't display more then what our ui can display

Comment (ZainabAlnajjar) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: @mostafa-n3ma in that case you are saving data that you won't display, that's a waste of memory

Comment (ZainabAlnajjar) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: I don't think we should let the user type anything they want, limiting them would be better in my opinion

Comment (haideraljawasim) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: @ZainabAlnajjar this just for text filed bug not related to view model or user max input these a different bug , we fixing here ui related bugs

Comment (ZainabAlnajjar) [reply app/src/main/java/com/sanaa/tudee_assistant/presentation/screen/tasks/addEditTask/AddEditTaskContent.kt:97]: @haideraljawasim @mostafa-n3ma ok, then please make the issue and pr description clearer for next time, the issue title is confusing

**Review by ZainabAlnajjar — APPROVED** [review]
