### PR TITLE
Hotfix/domain returned values

### LINKED ISSUE #60: Use Exceptions instead of bollean return  type
change each functions in services to us exceptions instead of boolean

### PR DESCRIPTION
**Pull request by haideraljawasim**
Add getTasksByCategoryCount 
Change return type to use exceptions instead of boolean

### CODE REVIEW

File: app/src/main/java/com/sanaa/tudee_assistant/domain/service/TaskService.kt [hunk 1]
```diff
@@ -4,12 +4,13 @@ import com.sanaa.tudee_assistant.domain.model.Task
...
 interface TaskService {
-    fun getTasks(): Flow<List<Task>>
     suspend fun addTask(task: Task)
-    suspend fun updateTask(task: Task): Boolean
-    suspend fun deleteTaskById(taskId: Int): Boolean
+    suspend fun updateTask(task: Task)
+    suspend fun deleteTaskById(taskId: Int)
     suspend fun deleteAllTasks()
     suspend fun getTaskById(taskId: Int): Task
+    suspend fun getTasksCountByCategory(categoryId: Int): Int
```
Comment (ZainabAlnajjar) [inline app/src/main/java/com/sanaa/tudee_assistant/domain/service/TaskService.kt]: getTasksCountByCategoryId

**Review by ZainabAlnajjar — APPROVED** [review]
