### PR TITLE
fix splash screen to be shown while the app is loading

### LINKED ISSUE #134: fix splash screen
make the splash screen work pased on the application theme and not the device theme, also keep it up until the all the needed date is fetched (including data from the preferance maneger)

### PR DESCRIPTION
**Pull request by ZainabAlnajjar**
## 🛠️ Summary

fix the splash screen to show it until the data is loaded then show the app screen

---

## 📌 Description

fix the splash screen to show it until the data is loaded then show the app screen

---

## ✅️Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactoring (no functional changes, renaming)

## ✅ Checklist:

- [x] The PR is to the `dev` branch
- [x] My code follows the style and architecture of the project
- [x] I have performed a self-review of my code
- [x] I tested the application on my computer and does everything as expected

---

## 🔍 Testing

Please check what has been verified before merging:

- [x] Code compiles successfully
- [x] Feature behaves as expected
- [x] Manually tested the affected logic

---
---

## 📎 Related Issues / Tasks

- Resolves: `#134`

### CODE REVIEW

File: app/src/main/java/com/sanaa/tudee_assistant/di/viewModelModule.kt [hunk 1]
```diff
@@ -14,7 +14,7 @@ import org.koin.core.module.dsl.viewModelOf
 import org.koin.dsl.module
 
 val viewModelModule = module {
-    viewModelOf(::TudeeAppViewModel)
+    viewModelOf(::MainViewModel)
```
Comment (mostafa-n3ma) [inline app/src/main/java/com/sanaa/tudee_assistant/di/viewModelModule.kt]: change this to MainActivityViewModel to be more specifec

**Review by diyar214 — DISMISSED** [review]
LGTM!

**Review by mostafa-n3ma — APPROVED** [review]

**Review by diyar214 — APPROVED** [review]
